# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "Develop" ]
  pull_request:
    branches: [ "Develop" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update 
        sudo apt-get install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

    - name: Get-Sub-repos
      run: git submodule update --remote --recursive
